apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: mern-frontend:v1 # Image you built locally
        ports:
        - containerPort: 5173 # Matches the EXPOSE 5173 from your Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes internally
      targetPort: 5173 # The port the container is listening on (from Dockerfile)
  type: NodePort # Exposes the service on a port on your Minikube VM